@TheHunt.Api_HostAddress = https://localhost:7244
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJmOTYyZDUxNy01ZTFjLTQwZGEtOWNjZC03NjNmNGM4YjFjNDgiLCJzdWIiOiJ1c2VybmFtZSIsInVzZXJpZCI6IjAxOWJjMzdjLWY1YmItNzI1Mi1iZDMxLThjNmEwZjMyNGJlNSIsImZyZWVfbWVtYmVyIjoidHJ1ZSIsIm5iZiI6MTc2ODUxMTMxMSwiZXhwIjoxNzY4NTEyMjExLCJpYXQiOjE3Njg1MTEzMTEsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwMzMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDExIn0.W5vxiYmEXh2Y1Q2i9KBdC37jMKpBLRy4dYaC9r4-vkw
@refresh = 2wy4Q56QiCizCea90EjSj7asEG7H189jlVwgceCOxELAABsCzkcwLArWpmBimdgI3048lVq8J4CLkE7lFH3NQg==


POST {{TheHunt.Api_HostAddress}}/locations/
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "latitude": 37.861523,
  "longitude": -87.385952
}

###

GET {{TheHunt.Api_HostAddress}}/locations/304c4a46-643f-4cc2-82fa-2332c2d3dbc7
Authorization: Bearer {{token}}
Accept: application/json

###

POST {{TheHunt.Api_HostAddress}}/places/
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "id": null,
  "name": "Place name",
  "locationId": "304c4a46-643f-4cc2-82fa-2332c2d3dbc7",
  "acceptedRadiusMeters": 5.0,
  "hint1": "East of downtown",
  "hint2": "Rhymes with orange",
  "hint3": "Famous crime happened here",
  "addedByUserId": null
}

###

GET {{TheHunt.Api_HostAddress}}/places/86386e16-db2f-420a-8c13-4c5a538ac0c5
Authorization: Bearer {{token}}
Accept: application/json


###

POST {{TheHunt.Api_HostAddress}}/register
Accept: application/json
Content-Type: application/json

{
  "email": "test@test.com", 
  "userName": "username",
  "password": "Test123?"
}

###

POST {{TheHunt.Api_HostAddress}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test123?"
}

###

POST {{TheHunt.Api_HostAddress}}/revoke
Accept: application/json
Content-Type: application/json

{ "refreshToken": "2wrnwL+bvJ5I9d35KmCjJCFBsc9WOCzNRBe+ANet1ZyXx61YMTbFdG40YHU49WbuF9wf1wfFVFEoq2Nli9Y3uQ==" }

###

POST {{TheHunt.Api_HostAddress}}/refresh
Accept: application/json
Content-Type: application/json

{ "refreshToken": "2wrnwL+bvJ5I9d35KmCjJCFBsc9WOCzNRBe+ANet1ZyXx61YMTbFdG40YHU49WbuF9wf1wfFVFEoq2Nli9Y3uQ==" }